// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/proto.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BIDDING_STATUS int32

const (
	BIDDING_STATUS_SUCCESS   BIDDING_STATUS = 0
	BIDDING_STATUS_FAIL      BIDDING_STATUS = 1
	BIDDING_STATUS_EXCEPTION BIDDING_STATUS = 2
)

// Enum value maps for BIDDING_STATUS.
var (
	BIDDING_STATUS_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
		2: "EXCEPTION",
	}
	BIDDING_STATUS_value = map[string]int32{
		"SUCCESS":   0,
		"FAIL":      1,
		"EXCEPTION": 2,
	}
)

func (x BIDDING_STATUS) Enum() *BIDDING_STATUS {
	p := new(BIDDING_STATUS)
	*p = x
	return p
}

func (x BIDDING_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BIDDING_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_proto_enumTypes[0].Descriptor()
}

func (BIDDING_STATUS) Type() protoreflect.EnumType {
	return &file_grpc_proto_proto_enumTypes[0]
}

func (x BIDDING_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BIDDING_STATUS.Descriptor instead.
func (BIDDING_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{0}
}

type AUCTION_STATUS int32

const (
	AUCTION_STATUS_ONGOING  AUCTION_STATUS = 0
	AUCTION_STATUS_FINISHED AUCTION_STATUS = 1
)

// Enum value maps for AUCTION_STATUS.
var (
	AUCTION_STATUS_name = map[int32]string{
		0: "ONGOING",
		1: "FINISHED",
	}
	AUCTION_STATUS_value = map[string]int32{
		"ONGOING":  0,
		"FINISHED": 1,
	}
)

func (x AUCTION_STATUS) Enum() *AUCTION_STATUS {
	p := new(AUCTION_STATUS)
	*p = x
	return p
}

func (x AUCTION_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AUCTION_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_proto_enumTypes[1].Descriptor()
}

func (AUCTION_STATUS) Type() protoreflect.EnumType {
	return &file_grpc_proto_proto_enumTypes[1]
}

func (x AUCTION_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AUCTION_STATUS.Descriptor instead.
func (AUCTION_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{1}
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidderName    string                 `protobuf:"bytes,1,opt,name=bidder_name,json=bidderName,proto3" json:"bidder_name,omitempty"`
	AuctionId     int64                  `protobuf:"varint,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // Input for the bid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetBidderName() string {
	if x != nil {
		return x.BidderName
	}
	return ""
}

func (x *BidRequest) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *BidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BidReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BiddingStatus BIDDING_STATUS         `protobuf:"varint,1,opt,name=bidding_status,json=biddingStatus,proto3,enum=auction.BIDDING_STATUS" json:"bidding_status,omitempty"`
	AuctionId     int64                  `protobuf:"varint,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	HighestBid    int64                  `protobuf:"varint,3,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // Used for logging --> If a bid is too low, the auction is finished etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidReply) Reset() {
	*x = BidReply{}
	mi := &file_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidReply) ProtoMessage() {}

func (x *BidReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidReply.ProtoReflect.Descriptor instead.
func (*BidReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{1}
}

func (x *BidReply) GetBiddingStatus() BIDDING_STATUS {
	if x != nil {
		return x.BiddingStatus
	}
	return BIDDING_STATUS_SUCCESS
}

func (x *BidReply) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *BidReply) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *BidReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_grpc_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{2}
}

func (x *ResultRequest) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

type ResultReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            AUCTION_STATUS         `protobuf:"varint,1,opt,name=status,proto3,enum=auction.AUCTION_STATUS" json:"status,omitempty"`
	AuctionId         int64                  `protobuf:"varint,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	CurrentHighestBid int64                  `protobuf:"varint,3,opt,name=current_highest_bid,json=currentHighestBid,proto3" json:"current_highest_bid,omitempty"`
	AuctionWinner     string                 `protobuf:"bytes,4,opt,name=auction_winner,json=auctionWinner,proto3" json:"auction_winner,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResultReply) Reset() {
	*x = ResultReply{}
	mi := &file_grpc_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultReply) ProtoMessage() {}

func (x *ResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultReply.ProtoReflect.Descriptor instead.
func (*ResultReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ResultReply) GetStatus() AUCTION_STATUS {
	if x != nil {
		return x.Status
	}
	return AUCTION_STATUS_ONGOING
}

func (x *ResultReply) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *ResultReply) GetCurrentHighestBid() int64 {
	if x != nil {
		return x.CurrentHighestBid
	}
	return 0
}

func (x *ResultReply) GetAuctionWinner() string {
	if x != nil {
		return x.AuctionWinner
	}
	return ""
}

type ReplicateBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	HighestBid    int64                  `protobuf:"varint,2,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	Winner        string                 `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
	Status        AUCTION_STATUS         `protobuf:"varint,4,opt,name=status,proto3,enum=auction.AUCTION_STATUS" json:"status,omitempty"`
	Sequence      int64                  `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateBidRequest) Reset() {
	*x = ReplicateBidRequest{}
	mi := &file_grpc_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateBidRequest) ProtoMessage() {}

func (x *ReplicateBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateBidRequest.ProtoReflect.Descriptor instead.
func (*ReplicateBidRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicateBidRequest) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *ReplicateBidRequest) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ReplicateBidRequest) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *ReplicateBidRequest) GetStatus() AUCTION_STATUS {
	if x != nil {
		return x.Status
	}
	return AUCTION_STATUS_ONGOING
}

func (x *ReplicateBidRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ReplicateBidReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Reason              string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                                         // for wrong sequence, out-of-date leader etc
	LastAppliedSequence int64                  `protobuf:"varint,3,opt,name=last_applied_sequence,json=lastAppliedSequence,proto3" json:"last_applied_sequence,omitempty"` // so the leader knows how far along this follower is
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReplicateBidReply) Reset() {
	*x = ReplicateBidReply{}
	mi := &file_grpc_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateBidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateBidReply) ProtoMessage() {}

func (x *ReplicateBidReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateBidReply.ProtoReflect.Descriptor instead.
func (*ReplicateBidReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicateBidReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicateBidReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReplicateBidReply) GetLastAppliedSequence() int64 {
	if x != nil {
		return x.LastAppliedSequence
	}
	return 0
}

type SyncStateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuctionId         int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	NodeId            int64                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LastKnownSequence int64                  `protobuf:"varint,3,opt,name=last_known_sequence,json=lastKnownSequence,proto3" json:"last_known_sequence,omitempty"`
	LeaderId          int64                  `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncStateRequest) Reset() {
	*x = SyncStateRequest{}
	mi := &file_grpc_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateRequest) ProtoMessage() {}

func (x *SyncStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateRequest.ProtoReflect.Descriptor instead.
func (*SyncStateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{6}
}

func (x *SyncStateRequest) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *SyncStateRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SyncStateRequest) GetLastKnownSequence() int64 {
	if x != nil {
		return x.LastKnownSequence
	}
	return 0
}

func (x *SyncStateRequest) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type SyncStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	HighestBid    int64                  `protobuf:"varint,2,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	AuctionWinner string                 `protobuf:"bytes,3,opt,name=auction_winner,json=auctionWinner,proto3" json:"auction_winner,omitempty"` // if finished --> if status = ONGOING it should be an empty string
	Status        AUCTION_STATUS         `protobuf:"varint,4,opt,name=status,proto3,enum=auction.AUCTION_STATUS" json:"status,omitempty"`
	LastSequence  int64                  `protobuf:"varint,5,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"` // highest sequence number included in this snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStateReply) Reset() {
	*x = SyncStateReply{}
	mi := &file_grpc_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateReply) ProtoMessage() {}

func (x *SyncStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateReply.ProtoReflect.Descriptor instead.
func (*SyncStateReply) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{7}
}

func (x *SyncStateReply) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *SyncStateReply) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *SyncStateReply) GetAuctionWinner() string {
	if x != nil {
		return x.AuctionWinner
	}
	return ""
}

func (x *SyncStateReply) GetStatus() AUCTION_STATUS {
	if x != nil {
		return x.Status
	}
	return AUCTION_STATUS_ONGOING
}

func (x *SyncStateReply) GetLastSequence() int64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

var File_grpc_proto_proto protoreflect.FileDescriptor

const file_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x10grpc/proto.proto\x12\aauction\"d\n" +
	"\n" +
	"BidRequest\x12\x1f\n" +
	"\vbidder_name\x18\x01 \x01(\tR\n" +
	"bidderName\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\x03R\tauctionId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\xa2\x01\n" +
	"\bBidReply\x12>\n" +
	"\x0ebidding_status\x18\x01 \x01(\x0e2\x17.auction.BIDDING_STATUSR\rbiddingStatus\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\x03R\tauctionId\x12\x1f\n" +
	"\vhighest_bid\x18\x03 \x01(\x03R\n" +
	"highestBid\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\".\n" +
	"\rResultRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\"\xb4\x01\n" +
	"\vResultReply\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.auction.AUCTION_STATUSR\x06status\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\x03R\tauctionId\x12.\n" +
	"\x13current_highest_bid\x18\x03 \x01(\x03R\x11currentHighestBid\x12%\n" +
	"\x0eauction_winner\x18\x04 \x01(\tR\rauctionWinner\"\xba\x01\n" +
	"\x13ReplicateBidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\x12\x1f\n" +
	"\vhighest_bid\x18\x02 \x01(\x03R\n" +
	"highestBid\x12\x16\n" +
	"\x06winner\x18\x03 \x01(\tR\x06winner\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.auction.AUCTION_STATUSR\x06status\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x03R\bsequence\"y\n" +
	"\x11ReplicateBidReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x122\n" +
	"\x15last_applied_sequence\x18\x03 \x01(\x03R\x13lastAppliedSequence\"\x97\x01\n" +
	"\x10SyncStateRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x03R\x06nodeId\x12.\n" +
	"\x13last_known_sequence\x18\x03 \x01(\x03R\x11lastKnownSequence\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x03R\bleaderId\"\xcd\x01\n" +
	"\x0eSyncStateReply\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\x12\x1f\n" +
	"\vhighest_bid\x18\x02 \x01(\x03R\n" +
	"highestBid\x12%\n" +
	"\x0eauction_winner\x18\x03 \x01(\tR\rauctionWinner\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.auction.AUCTION_STATUSR\x06status\x12#\n" +
	"\rlast_sequence\x18\x05 \x01(\x03R\flastSequence*6\n" +
	"\x0eBIDDING_STATUS\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x02*+\n" +
	"\x0eAUCTION_STATUS\x12\v\n" +
	"\aONGOING\x10\x00\x12\f\n" +
	"\bFINISHED\x10\x012w\n" +
	"\x0eAuctionService\x12-\n" +
	"\x03Bid\x12\x13.auction.BidRequest\x1a\x11.auction.BidReply\x126\n" +
	"\x06Result\x12\x16.auction.ResultRequest\x1a\x14.auction.ResultReply2\x9f\x01\n" +
	"\x12ReplicationService\x12H\n" +
	"\fReplicateBid\x12\x1c.auction.ReplicateBidRequest\x1a\x1a.auction.ReplicateBidReply\x12?\n" +
	"\tSyncState\x12\x19.auction.SyncStateRequest\x1a\x17.auction.SyncStateReplyB\x19Z\x17tacoterror/grpc;auctionb\x06proto3"

var (
	file_grpc_proto_proto_rawDescOnce sync.Once
	file_grpc_proto_proto_rawDescData []byte
)

func file_grpc_proto_proto_rawDescGZIP() []byte {
	file_grpc_proto_proto_rawDescOnce.Do(func() {
		file_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)))
	})
	return file_grpc_proto_proto_rawDescData
}

var file_grpc_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_proto_proto_goTypes = []any{
	(BIDDING_STATUS)(0),         // 0: auction.BIDDING_STATUS
	(AUCTION_STATUS)(0),         // 1: auction.AUCTION_STATUS
	(*BidRequest)(nil),          // 2: auction.BidRequest
	(*BidReply)(nil),            // 3: auction.BidReply
	(*ResultRequest)(nil),       // 4: auction.ResultRequest
	(*ResultReply)(nil),         // 5: auction.ResultReply
	(*ReplicateBidRequest)(nil), // 6: auction.ReplicateBidRequest
	(*ReplicateBidReply)(nil),   // 7: auction.ReplicateBidReply
	(*SyncStateRequest)(nil),    // 8: auction.SyncStateRequest
	(*SyncStateReply)(nil),      // 9: auction.SyncStateReply
}
var file_grpc_proto_proto_depIdxs = []int32{
	0, // 0: auction.BidReply.bidding_status:type_name -> auction.BIDDING_STATUS
	1, // 1: auction.ResultReply.status:type_name -> auction.AUCTION_STATUS
	1, // 2: auction.ReplicateBidRequest.status:type_name -> auction.AUCTION_STATUS
	1, // 3: auction.SyncStateReply.status:type_name -> auction.AUCTION_STATUS
	2, // 4: auction.AuctionService.Bid:input_type -> auction.BidRequest
	4, // 5: auction.AuctionService.Result:input_type -> auction.ResultRequest
	6, // 6: auction.ReplicationService.ReplicateBid:input_type -> auction.ReplicateBidRequest
	8, // 7: auction.ReplicationService.SyncState:input_type -> auction.SyncStateRequest
	3, // 8: auction.AuctionService.Bid:output_type -> auction.BidReply
	5, // 9: auction.AuctionService.Result:output_type -> auction.ResultReply
	7, // 10: auction.ReplicationService.ReplicateBid:output_type -> auction.ReplicateBidReply
	9, // 11: auction.ReplicationService.SyncState:output_type -> auction.SyncStateReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_proto_proto_init() }
func file_grpc_proto_proto_init() {
	if File_grpc_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_grpc_proto_proto_goTypes,
		DependencyIndexes: file_grpc_proto_proto_depIdxs,
		EnumInfos:         file_grpc_proto_proto_enumTypes,
		MessageInfos:      file_grpc_proto_proto_msgTypes,
	}.Build()
	File_grpc_proto_proto = out.File
	file_grpc_proto_proto_goTypes = nil
	file_grpc_proto_proto_depIdxs = nil
}
